source "https://rubygems.org"

gem "csv"
gem "logger"
gem "base64"
gem "bigdecimal"
gem "jekyll-sitemap"
gem "jekyll-paginate"
gem "jekyll-spaceship"

gem "jekyll", "~> 3.10.0"

gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "kramdown-parser-gfm"

gem "jekyll-remote-theme"